import { Plus_Jakarta_Sans, Cormorant_Garamond,Roboto } from 'next/font/google'
import "../scss/_global.scss"
import "bootstrap/dist/css/bootstrap.min.css";
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import BlogProvider from '@/context/blogs.context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const plus = Plus_Jakarta_Sans({ subsets: ['latin'] });
export const cormo = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

export const roboto = Roboto({
  subsets: ['latin'],
  weight:['100','300','400','500','700','900']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plus.className}>
        <BlogProvider>
        <Header/>
        {children}
        <Footer/>
        </BlogProvider>
        </body>
    </html>
  )
}
