import "../scss/_global.scss"
import "bootstrap/dist/css/bootstrap.min.css";
import {roboto} from '@/app/fonts/font'
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import BlogProvider from '@/context/blogs.context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <BlogProvider>
        <Header/>
        {children}
        <Footer/>
        </BlogProvider>
        </body>
    </html>
  )
}
