import { Inter } from 'next/font/google'
import "../scss/style.scss"
import Link from 'next/link';
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">salm</Link>
        {children}
        </body>
    </html>
  )
}
